# примеры API-запросов

@baseUrl = http://localhost:3000/api

### Создание пользователя-админа
POST {{baseUrl}}/users/admin/register
Content-Type: application/json

{
  "login": "admin01",
  "email": "email01@11.rr",
  "firstName": "admin",
  "password1": "123",
  "password2": "123",
  "role": "admin"
}

### Создание пользователя-менеджера
POST {{baseUrl}}/users/admin/register
Content-Type: application/json

{
  "login": "manager05",
  "email": "mager05@11.rr",
  "firstName": "manag",
  "password1": "1234",
  "password2": "1234",
  "role": "manager"
}

### Создание пользователя-клиента
POST {{baseUrl}}/users/client/register
Content-Type: application/json

{
  "login": "client2",
  "email": "client2@11.rr",
  "firstName": "cl1",
  "password1": "123",
  "password2": "123",
  "role": "admin"
}

### Получение информации о пользователе
GET {{baseUrl}}/users/4
Content-Type: application/json

### Поиск пользователей-админов
# (доступно только админам)
GET {{baseUrl}}/users/admin?name=admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIxIiwiZW1haWwiOiJlbWFpbEAxMS5yciIsImxvZ2luIjoiYWRtaW4wMiIsIm5hbWUiOiJhZG1pbjAyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAyNTA0NzcxLCJleHAiOjE3MDI1MDgzNzF9.85gcg0SuqoNLMCWvE7S12BBjn0xlIyZ2rlTfcex3dQA

### Поиск пользователей-менеджеров
# (доступно только менеджерам)
GET {{baseUrl}}/users/manager?offset=1&limit=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI0IiwiZW1haWwiOiJtYWdlcjA1QDExLnJyIiwibG9naW4iOiJtYW5hZ2VyMDUiLCJuYW1lIjoibWFuYWdlcjA1Iiwicm9sZSI6Im1hbmFnZXIiLCJpYXQiOjE3MDI1MDY3ODEsImV4cCI6MTcwMjUxMDM4MX0.6GYrwUGaC4k02kfzT5T4e9yqtRcrwaTXMcs7IPZG3X0

### Аутентификация
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "login": "client1",
  "password": "123"
}

### Получение токена при аутентификации
# (для админа) 
POST {{baseUrl}}/users/token
Content-Type: application/json

{
  "login": "admin02",
  "password": "123"
}

### (для манагера)
POST {{baseUrl}}/users/token
Content-Type: application/json

{
  "login": "manager05",
  "password": "1234"
}

### (для клиента)
POST {{baseUrl}}/users/token
Content-Type: application/json

{
  "login": "client2",
  "password": "123"
}


### Профиль пользователя 
# (доступен только после аутентификации - по токену)
GET {{baseUrl}}/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIxIiwiZW1haWwiOiJlbWFpbEAxMS5yciIsImxvZ2luIjoiYWRtaW4wMiIsIm5hbWUiOiJhZG1pbjAyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAyNTA0NzcxLCJleHAiOjE3MDI1MDgzNzF9.85gcg0SuqoNLMCWvE7S12BBjn0xlIyZ2rlTfcex3dQA

