# примеры API-запросов

@baseUrl = http://localhost:3000/api

### Создание пользователя-админа
POST {{baseUrl}}/users/admin/register
Content-Type: application/json

{
  "login": "admin111",
  "email": "email111@11.rr",
  "firstName": "admin",
  "password1": "123",
  "password2": "123",
  "role": "admin"
}

### Создание пользователя-менеджера
POST {{baseUrl}}/users/admin/register
Content-Type: application/json

{
  "login": "manager05",
  "email": "mager05@11.rr",
  "firstName": "manag",
  "password1": "1234",
  "password2": "1234",
  "role": "manager"
}

### Создание пользователя-клиента
POST {{baseUrl}}/users/client/register
Content-Type: application/json

{
  "login": "client2",
  "email": "client2@11.rr",
  "firstName": "cl1",
  "password1": "123",
  "password2": "123",
  "role": "admin"
}

### Получение информации о пользователе
GET {{baseUrl}}/users/6
Content-Type: application/json

### Поиск пользователей-админов
# (доступно только админам)
GET {{baseUrl}}/users/admin?name=admin0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIxIiwiZW1haWwiOiJlbWFpbEAxMS5yciIsImxvZ2luIjoiYWRtaW4wMiIsIm5hbWUiOiJhZG1pbjAyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAyNTk0NzEzLCJleHAiOjE3MDI1OTgzMTN9.8QUqNql36Fh7PhxYjmwxKKmqCf8b538RC_QDbUG7qMM

### Поиск пользователей-менеджеров
# (доступно только менеджерам)
GET {{baseUrl}}/users/manager?offset=1&limit=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6Im1hbmFnZXIwMiIsImVtYWlsIjoiZW1haWxAMTEucnIiLCJuYW1lIjoibWFuYWdlcjAyIiwicm9sZSI6Im1hbmFnZXIiLCJfaWQiOjQsImlhdCI6MTcwMjU5MDA2MywiZXhwIjoxNzAyNTkzNjYzfQ.dHBH64OgTTJUWoi_1Kp2reebNVMgNKeWhTiIqJ5xIMo

### Аутентификация
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "login": "client1",
  "password": "123"
}

### Получение токена при аутентификации
# (для админа) 
POST {{baseUrl}}/users/token
Content-Type: application/json

{
  "login": "admin02",
  "password": "123"
}

### (для манагера)
POST {{baseUrl}}/users/token
Content-Type: application/json

{
  "login": "manager05",
  "password": "1234"
}

### (для клиента)
POST {{baseUrl}}/users/token
Content-Type: application/json

{
  "login": "client2",
  "password": "123"
}


### Профиль пользователя 
# (доступен только после аутентификации - по токену)
GET {{baseUrl}}/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIxIiwiZW1haWwiOiJlbWFpbEAxMS5yciIsImxvZ2luIjoiYWRtaW4wMiIsIm5hbWUiOiJhZG1pbjAyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAyNTk0NzEzLCJleHAiOjE3MDI1OTgzMTN9.8QUqNql36Fh7PhxYjmwxKKmqCf8b538RC_QDbUG7qMM

