# примеры API-запросов

@baseUrl = http://localhost:3000/api

### Создание брони
# (только клиенты)
POST {{baseUrl}}/reservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1IiwiZW1haWwiOiJjbGllbnQxQDExLnJyIiwibG9naW4iOiJjbGllbnQxIiwibmFtZSI6ImNsaWVudDEiLCJyb2xlIjoiY2xpZW50IiwiaWF0IjoxNzAyNTk1ODEyLCJleHAiOjE3MDI1OTk0MTJ9.nAJIdM5QmcA_Eato6ztT-mN3E581yA_Tu4VmVY7bFtI

{
	"roomId": "5",
	"dateStart": "2023-12-19",
	"dateEnd": "2023-12-21",
	"description": "Профессиональный праздник"
}

### Список всех броней
# (только менеджеры)
GET {{baseUrl}}/reservations/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI0IiwiZW1haWwiOiJtYWdlcjA1QDExLnJyIiwibG9naW4iOiJtYW5hZ2VyMDUiLCJuYW1lIjoibWFuYWdlcjA1Iiwicm9sZSI6Im1hbmFnZXIiLCJpYXQiOjE3MDI1OTUzMzAsImV4cCI6MTcwMjU5ODkzMH0.ih5ryXOw1mh-fJlTFZXHZPrGeUGWLiqZUubIzsEztUs

### Список броней пользователя
# (только менеджеры)
GET {{baseUrl}}/reservations/user/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI0IiwiZW1haWwiOiJtYWdlcjA1QDExLnJyIiwibG9naW4iOiJtYW5hZ2VyMDUiLCJuYW1lIjoibWFuYWdlcjA1Iiwicm9sZSI6Im1hbmFnZXIiLCJpYXQiOjE3MDI1OTUzMzAsImV4cCI6MTcwMjU5ODkzMH0.ih5ryXOw1mh-fJlTFZXHZPrGeUGWLiqZUubIzsEztUs

### Информация по конкретной брони
GET {{baseUrl}}/reservations/1
Content-Type: application/json

### Обновление брони
# (только клиент-собственник или менеджер)
PUT {{baseUrl}}/reservations/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI0IiwiZW1haWwiOiJtYWdlcjA1QDExLnJyIiwibG9naW4iOiJtYW5hZ2VyMDUiLCJuYW1lIjoibWFuYWdlcjA1Iiwicm9sZSI6Im1hbmFnZXIiLCJpYXQiOjE3MDI1OTUzMzAsImV4cCI6MTcwMjU5ODkzMH0.ih5ryXOw1mh-fJlTFZXHZPrGeUGWLiqZUubIzsEztUs

{
	"dateStart": "2023-12-18T00:00:00.000Z",
	"dateEnd": "2023-12-22T00:00:00.000Z",
	"description": "+1 человек"
}

### Удаление брони
# (только клиент-собственник или менеджер)
DELETE {{baseUrl}}/reservations/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI0IiwiZW1haWwiOiJtYWdlcjA1QDExLnJyIiwibG9naW4iOiJtYW5hZ2VyMDUiLCJuYW1lIjoibWFuYWdlcjA1Iiwicm9sZSI6Im1hbmFnZXIiLCJpYXQiOjE3MDI1OTUzMzAsImV4cCI6MTcwMjU5ODkzMH0.ih5ryXOw1mh-fJlTFZXHZPrGeUGWLiqZUubIzsEztUs


###