# примеры API-запросов

@baseUrl = http://localhost:3000/api

### Создание гостиницы
# (только админы)
POST {{baseUrl}}/hotels/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIxIiwiZW1haWwiOiJlbWFpbEAxMS5yciIsImxvZ2luIjoiYWRtaW4wMiIsIm5hbWUiOiJhZG1pbjAyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAyNTA3MDA0LCJleHAiOjE3MDI1MTA2MDR9.Gstnv81K8Xgf83NTJMF7JRVR9hIKzEJW--ESG1HnYU4

{
	"title": "Гостиница TopHotel",
	"description": "5 звезд"
}

### Добавление номера гостиницы
# (только менеджеры)
POST {{baseUrl}}/hotels/rooms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI0IiwiZW1haWwiOiJtYWdlcjA1QDExLnJyIiwibG9naW4iOiJtYW5hZ2VyMDUiLCJuYW1lIjoibWFuYWdlcjA1Iiwicm9sZSI6Im1hbmFnZXIiLCJpYXQiOjE3MDI1MDczMDMsImV4cCI6MTcwMjUxMDkwM30.BggWi7UUU9q4MsjUOCBs01UNUBGk5T079oqr1k88hiM

{
	"hotel": "3",
	"title": "double",
	"description": "Дабл с балконом",
	"services": ["ванная", "2-спальная кровать", "фен", "балкон"]
}

### 2й пример
POST {{baseUrl}}/hotels/rooms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI0IiwiZW1haWwiOiJtYWdlcjA1QDExLnJyIiwibG9naW4iOiJtYW5hZ2VyMDUiLCJuYW1lIjoibWFuYWdlcjA1Iiwicm9sZSI6Im1hbmFnZXIiLCJpYXQiOjE3MDI1MDczMDMsImV4cCI6MTcwMjUxMDkwM30.BggWi7UUU9q4MsjUOCBs01UNUBGk5T079oqr1k88hiM

{
	"hotel": "3",
	"title": "single",
	"description": "Просто сингл",
	"services": ["душ", "1-спальная кровать", "фен"]
}

### Список гостиниц
GET {{baseUrl}}/hotels/
Content-Type: application/json

### Информация по конкретной гостинице
GET {{baseUrl}}/hotels/2
Content-Type: application/json

### Список номеров по конкретной гостинице
### (только доступные - isEnabled=true)
GET {{baseUrl}}/hotels/3/rooms?offset=0&limit=0
Content-Type: application/json

### Информация по конкретному номеру
GET {{baseUrl}}/hotels/rooms/3
Content-Type: application/json

### Обновление гостиницы
# (только админы)
PUT {{baseUrl}}/hotels/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIxIiwiZW1haWwiOiJlbWFpbEAxMS5yciIsImxvZ2luIjoiYWRtaW4wMiIsIm5hbWUiOiJhZG1pbjAyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAyNTA3MDA0LCJleHAiOjE3MDI1MTA2MDR9.Gstnv81K8Xgf83NTJMF7JRVR9hIKzEJW--ESG1HnYU4

{
	"title": "Госиница TopHotel+"
}

### Обновление номера гостиницы
# (только менеджеры)
PUT {{baseUrl}}/hotels/rooms/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI0IiwiZW1haWwiOiJtYWdlcjA1QDExLnJyIiwibG9naW4iOiJtYW5hZ2VyMDUiLCJuYW1lIjoibWFuYWdlcjA1Iiwicm9sZSI6Im1hbmFnZXIiLCJpYXQiOjE3MDI1MDczMDMsImV4cCI6MTcwMjUxMDkwM30.BggWi7UUU9q4MsjUOCBs01UNUBGk5T079oqr1k88hiM

{
	"isEnabled": "false"
}


### Удаление гостиницы
# (только админы)
DELETE {{baseUrl}}/hotels/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIxIiwiZW1haWwiOiJlbWFpbEAxMS5yciIsImxvZ2luIjoiYWRtaW4wMiIsIm5hbWUiOiJhZG1pbjAyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzAyNTA3MDA0LCJleHAiOjE3MDI1MTA2MDR9.Gstnv81K8Xgf83NTJMF7JRVR9hIKzEJW--ESG1HnYU4

### Поиск гостиниц
# GET
GET {{baseUrl}}/hotels/search?title=&offset=0
Content-Type: application/json

### POST
POST {{baseUrl}}/hotels/search
Content-Type: application/json

{
	"title": "Top"
}

### Поиск номеров гостиниц
# GET
GET {{baseUrl}}/hotels/rooms/search?title=&offset=0
Content-Type: application/json

### POST
POST {{baseUrl}}/hotels/rooms/search
Content-Type: application/json

{
	"title": "double",
	"services": ["душ"]
}

